#Para crear un contenedor docker con una solo instancias
#docker run -d -p 4444:4444 -p 7900:7900 --shm-size="2g" selenium/standalone-chrome:latest
#docker run -d -p 4444:4444 -p 7900:7900 --shm-size="2g" selenium/standalone-firefox:latest
#docker run -d -p 4444:4444 -p 7900:7900 --shm-size="2g" selenium/standalone-edge:latest

#Ejecutar desde la consola colocada en la carpeta del archivo: 
#docker-compose up -d 
#o
#docker-compose -f <docker-compose.yml> logs

version: '3'
services:
  selenium-hub:
    image: selenium/hub:3.141.59
    container_name: selenium-hub
    ports:
      - "4444:4444"

  selenium-chrome:
    image: selenium/node-chrome-debug:3.141.59
    container_name: selenium-chrome
    ports:
      - "5901:5900" # VNC
    environment:
      - HUB_HOST=selenium-hub
      - NODE_MAX_INSTANCES=1
      - NODE_MAX_SESSION=1
      - DISPLAY=:99
    depends_on:
      - selenium-hub
    volumes:
      - ./videos:/videos

  video:
    image: selenium/video:ffmpeg-4.3.1-20230403
    container_name: video
    depends_on:
      - selenium-chrome
    environment:
      - DISPLAY_CONTAINER_NAME=selenium-chrome
      - FILE_NAME=test_run.mp4
    volumes:
      - ./videos:/videos